# Generated by Django 3.0.5 on 2021-03-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('price', models.IntegerField()),
                ('location', models.CharField(max_length=2000)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
