# Generated by Django 3.0.5 on 2021-03-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
                ('Location', models.CharField(max_length=100)),
                ('Main_Info', models.TextField()),
                ('Itinerary', models.TextField()),
                ('Country_Name', models.CharField(max_length=2000)),
            ],
        ),
        migrations.DeleteModel(
            name='Packages',
        ),
    ]
