# Generated by Django 3.0.5 on 2021-03-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20210323_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='picture',
            field=models.FileField(null=True, upload_to='static/images/uploads'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='Country_Name',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='Itinerary',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='Location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='Main_Info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='Price',
            field=models.IntegerField(null=True),
        ),
    ]
