# Generated by Django 3.0.5 on 2021-04-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20210323_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bradcam', models.FileField(null=True, upload_to='static/uploads')),
                ('tourname', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('Itenary', models.TextField(null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('days', models.IntegerField(null=True)),
                ('reviews', models.IntegerField(max_length=5, null=True)),
            ],
        ),
    ]
