# Generated by Django 3.0.5 on 2021-04-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_tourdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TourDetail',
        ),
        migrations.AddField(
            model_name='tour',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='reviews',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
