# Generated by Django 3.0.5 on 2021-04-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20210402_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='itinerary',
        ),
        migrations.AddField(
            model_name='tour',
            name='itinerary',
            field=models.ManyToManyField(to='application.Itenerary'),
        ),
    ]
