# Generated by Django 3.0.5 on 2021-04-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20210403_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tour', models.ManyToManyField(to='application.Tour')),
            ],
        ),
        migrations.DeleteModel(
            name='slider',
        ),
    ]
