# Generated by Django 3.0.5 on 2021-04-03 15:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_auto_20210403_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='tour',
        ),
        migrations.AddField(
            model_name='destination',
            name='tour',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='application.Tour'),
            preserve_default=False,
        ),
    ]
