# Generated by Django 3.0.5 on 2021-04-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_auto_20210403_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='tour',
        ),
        migrations.AddField(
            model_name='destination',
            name='tour',
            field=models.ManyToManyField(default=None, to='application.Tour'),
        ),
    ]
