# Generated by Django 3.0.5 on 2021-04-03 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_auto_20210403_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='destination',
        ),
        migrations.AddField(
            model_name='tour',
            name='destination',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='application.Destination'),
        ),
    ]
