# Generated by Django 3.0.5 on 2021-04-06 05:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0018_auto_20210406_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='reviews',
        ),
        migrations.AddField(
            model_name='tour',
            name='reviews',
            field=models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
