# Generated by Django 3.0.5 on 2021-04-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0019_auto_20210406_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
