# Generated by Django 3.0.5 on 2021-04-06 17:07

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_tour_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='country_Name',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
