# Generated by Django 3.0.5 on 2021-04-06 17:12

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0021_auto_20210406_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='country_Name',
            field=django_countries.fields.CountryField(max_length=2000, null=True),
        ),
    ]
